server:
  port: 7003 # eureka 服务端口号

eureka:
  instance:
    hostname: eureka7002.com  # 配置主机映射需
    # hostname: localhost # eureka 服务器域名，这里是本机localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7002/eureka/