#eureka:
#  client:
#    service-url:
#      defaultZone:   http://eureka7001.com:7001/eureka/
#      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/http://eureka7003.com:7003/eureka/
#      # defaultZone:   http://127.0.0.1:7001/eureka/ # eureka 注册中心地址
#  instance:
#    instance-id: eureka-server-prover-provider-test-8081 # 修改映射主机名称
#    prefer-ip-address: true # 访问路径可以显示ip地址

spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mp?useUnicode=true&characterEncoding=UTF8
      username: root
      password: 1234
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      max-open-prepared-statements: 50
  application:
    name: service-one  # 设置改微服务的名字
  activemq:
    broker-url: tcp://192.168.112.107:61616
    user: admin
    password: admin
    pool:
      enabled: false
      max-connections: 10
  jms:
    pub-sub-domain: false   # false =Queue  true=Topic
    # pub-sub-domain: false   # false =Queue  true=Topic
myqueue: boot-activemq-queue   # 定义队列名称
topicName: publish.topic
server:
  port: 8081
mybatis-plus:
  mapper-locations: classpath*:com/wu/kong/dao/mapping/*.xml
  type-aliases-package: com.wu.kong.model
  global-config:
    id-type: 0 #数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: true
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector #逻辑删除
    logic-delete-value: -1
    logic-not-delete-value: 1
    meta-object-handler: com.wu.kong.config.MyMetaObjectHandler    # 自定义公共字段填充器
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false  # 配置缓存的全局开关

