server:
  port: 7001 # eureka 服务端口号

eureka:
  instance:
    hostname: eureka7001.com  # 配置主机映射需
  # hostname: localhost # eureka 服务器域名，这里是本机localhost
  client:
    register-with-eureka: false   # false表示不向注册中心注册自己
    fetch-registry: false   # false 表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      # defaultZone: http://${eureka.instance.hostname}:7001/eureka/

spring:
  application:
    name: eureka-service